- name: list operation with vars file
  hosts: localhost
  vars:
    list1: "{{ list1 }}"
    list2: "{{ list2 }}"

  # print the list

  tasks:

  - name: Split the list
    debug:
      msg:
      - "First Part: {{ list1[:3] }}"
      - "Second Part: {{ list1[3:] }}"

  # combine the two lists

  - name: Combine the two lists
    debug:
      vars: "{{ list1 + list2 }}"
