- name: list operation with vars file
  hosts: localhost

  # create the list by passing the variables from extra vars 

  tasks:

  - name: create the list by passing the variables from extra vars
    debug:
      msg: "{{ list2 }}"
