- name: list operation with vars file
  hosts: localhost
  vars_files: vars_list.yml

  # merge the two lists

  tasks:
  - name: merge the two lists
    debug:
      msg: "{{ list1 | union(list2) }}"
    tags: merge_list
    register: merged_lists

  - name: print the merged list
    debug:
      msg: "Merged list is {{ merged_lists }}"
