---
- name: create the list by passing the variables from extra vars
  hosts: localhost
  vars:
    list_var: []

  tasks:
  - name: create a list
    debug:
      msg:
      - "list: {{ list_var }}"
      - "length of list is: {{ list_var | length }}"
