- name: list operation with vars file
  hosts: localhost
  vars_files:
  - vars_list.yml
  # create the list by passing the variables from vars_files

  tasks:
  - name: print the list
    debug:
      msg: "list: {{ list1 }}, length of list is: {{ list1 | length }}"
