- name: Split List Operation
  hosts: localhost
  vars:
    my_list: []
    split_size: []

  vars_prompt:
  - name: "list"
    prompt: " Enter the list "
    private: False

  - name: "split_size"
    prompt: "Enter the size of list to split"
    private: False

  tasks:
  - name: "my_list"
    set_fact:
      my_list: "{{ list.split(',') | map('int') | list }}"

  - name: "list_size"
    set_fact:
      split_size: "{{ split_size.split(',') | map('int') | list }}"

  - name: "print my_list"
    debug:
      msg: "{{ my_list}}, length: {{ my_list | length }}"

  - name: "print split_size"
    debug:
      msg: "{{ split_size }}, length: {{ split_size | length }}"
