- name: Split List Operation
  hosts: localhost

  vars:
    list: []
    size: []

  tasks:

  - name: ensure my_list in integer
    set_fact:
      my_list: "{{ list | map('int') | list }}"

  - name: ensure split_size in integer
    set_fact:
      split_size: "{{ size | map('int') | list }}"

  - name: Print my_list
    debug:
      msg: "my_list: {{my_list}}, length: {{my_list | length}}"

  - name: Print split_size
    debug:
      msg: "split_size: {{split_size}}, length: {{split_size | length}}"

  - name: Split my_list based on split_size
    set_fact:
      split_lists: []

  - name: Split and print lists
    set_fact:
      split_lists: "{{ split_lists + [my_list[list_index: list_index + item]] }}"
    loop: "{{ split_size }}"
    loop_control:
      index_var: list_index

  - name: Print split lists
    debug:
      msg: "{{ split_lists }}"
