- name: List files and directories separately
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Find directories in the current directory
    find:
      paths: "/home/lalit"
      file_type: directory
    register: dir_list

  - name: Find files in the current directory
    find:
      paths: "/home/learning/list_operations"
      file_type: file
    register: file_list

  - name: Show directories
    debug:
      msg: "Directories: {{ dir_list.files }}"

  - name: Show files
    debug:
      msg: "Files: {{ file_list.files }}"
