- name: write an ansible task to list of the file and folder for the current directory
  hosts: localhost
  tasks:
  - name: Show the file & directory in the current directory
    command: ls
    register: dir_output

  - name: Show Files & Directory in the Current Directroy
    debug:
      var: dir_output.stdout_lines
